name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log In To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Build And Push Docker Image
#        run: |
#          docker buildx build --platform linux/amd64,linux/arm64 \
#            -t jjalseu/devlounge:latest \
#            -t jjalseu/devlounge:${{github.sha}} \
#            --push -f ./Dockerfile --target production .
      - name: Install SSH Key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" | tr -d '\r' > so-precious-pie.pem
          chmod 400 so-precious-pie.pem

      - name: Deploy to EC2
        run: |
          ssh -i so-precious-pie.pem -o StrictHostKeyChecking=no ec2-user@ec2-13-125-27-88.ap-northeast-2.compute.amazonaws.com << 'EOF'
          
          cd /home/ec2-user/devlounge-app
          
          sudo docker-compose stop app
          sudo docker-compose rm -f app
          
          sudo docker-compose pull app
          sudo docker-compose up -d app
          
          EOF
